const e=escapeHTML;
const paths={
 tray:'<path d="M4 4h16l2 10v6H2v-6L4 4Z"/><path d="M2 14h6l2 3h4l2-3h6"/>',
 packet:'<path d="M7 7h13v14H7z"/><path d="M4 17H2V2h13v2M10 11h7m-7 4h5"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 activity:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5m4-1v5l3 2"/>',
 source:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/><path d="M7 14v3h3m7-7V7h-3"/>',
 help:'<circle cx="12" cy="12" r="9"/><path d="M9.6 8.5a2.6 2.6 0 1 1 4.1 2.1c-1.2.7-1.7 1.2-1.7 2.4m0 3v.1"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>', back:'<path d="M20 12H4m6-6-6 6 6 6"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',down:'<path d="m6 9 6 6 6-6"/>',
 file:'<path d="M14 2H5v20h14V7l-5-5Z"/><path d="M14 2v5h5M8 12h8m-8 4h6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 2 8 3v6c0 5-5 9-8 11-3-2-8-6-8-11V5l8-3Z"/><path d="m8 11 3 3 5-5"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 filter:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r="2" fill="currentColor" stroke="none"/><circle cx="10" cy="18" r="2" fill="currentColor" stroke="none"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',
 upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 alert:'<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.1"/>',
 mail:'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m3 6 9 7 9-7"/>',
 building:'<path d="M4 21V3h16v18M2 21h20M8 7h2m4 0h2M8 11h2m4 0h2M9 21v-6h6v6"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 refresh:'<path d="M20 7a9 9 0 0 0-15-2L2 8m0-5v5h5m-3 9a9 9 0 0 0 15 2l3-3m0 5v-5h-5"/>',
 eye:'<path d="M2 12S6 5 12 5s10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 dot:'<circle cx="12" cy="12" r="2" fill="currentColor" stroke="none"/>',
 pause:'<path d="M9 5v14M15 5v14"/>',note:'<path d="M4 3h16v14l-4 4H4V3Z"/><path d="M8 8h8M8 12h6m2 9v-4h4"/>',
 copy:'<rect x="8" y="8" width="12" height="13" rx="1"/><path d="M5 17H3V3h12v2"/>',
 external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.file}</svg>`;
const STORAGE='mahogany.workspace.v1';
let state={version:VERSION,loads:copy(SEED)},storageOK=true,recovered=false;
try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw);if(isValidState(parsed))state=parsed;else recovered=true;}}catch{recovered=true;storageOK=false;}
let route='queue',loadId='',query='',tab='all',filter='all',sort='oldest',filtersOpen=false,selectedDoc='',zoom=100,modalContext=null,previousFocus=null,toastTimer=null,mobileOpen=false,pendingImport=[];
const $=sel=>document.querySelector(sel), getLoad=id=>state.loads.find(l=>l.id===id), currentLoad=()=>getLoad(loadId);
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(state));storageOK=true;}catch{storageOK=false;toast('Browser storage is full or unavailable. These changes are only in memory.',true);}}
function updateLoad(next){const i=state.loads.findIndex(l=>l.id===next.id);if(i!==-1){state.loads[i]=next;persist();render();}}
function toast(text,error=false){clearTimeout(toastTimer);$('#toasts').innerHTML=`<div class="toast ${error?'error':''}" role="status">${icon(error?'alert':'check')}<span>${e(text)}</span></div>`;toastTimer=setTimeout(()=>$('#toasts').innerHTML='',5200);}
function formatTime(iso){if(!iso)return'Not checked';try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Chicago'}).format(new Date(iso))+' CT';}catch{return'Unknown time';}}
function dateOnly(iso){try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'America/Chicago'}).format(new Date(iso));}catch{return'—';}}
function badge(a){const s=STATUS[a.state];return`<span class="tag ${s.tone}"><span class="dot"></span>${s.label}</span>`;}
function button(label,action,kind='secondary',ico='',extra=''){return`<button class="btn ${kind}" data-action="${action}" ${extra}>${ico&&ico!=='arrow'?icon(ico):''}${label}</button>`;}
function readRoute(){const pieces=location.hash.replace(/^#\/?/,'').split('/');route=['queue','packets','activity','sources','load'].includes(pieces[0])?pieces[0]:'queue';loadId=pieces[1]||'';if(route==='load'&&!getLoad(loadId)){route='queue';loadId='';}selectedDoc='';zoom=100;mobileOpen=false;render();window.scrollTo({top:0,behavior:'instant'});}
function go(hash){if(location.hash===hash){readRoute();}else location.hash=hash;}
function shell(content){
 const ready=state.loads.filter(l=>assess(l).ready).length,need=state.loads.length-ready;
 const current=route==='load'?'Review queue':({queue:'Review queue',packets:'Ready packets',activity:'Activity',sources:'Sources'}[route]);
 const nav=(name,label,ico,count)=>`<a class="nav-item ${route===name||(name==='queue'&&route==='load')?'active':''}" href="#/${name}" ${route===name?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${count!==undefined?`<span class="nav-count">${count}</span>`:''}</a>`;
 return`<a class="skip" href="#main" data-action="skip-main">Skip to workspace</a>${mobileOpen?'<div class="backdrop-mobile" data-action="menu"></div>':''}<aside class="sidebar ${mobileOpen?'open':''}" aria-label="Primary navigation"><a href="#/queue" class="brand" aria-label="MAHOGANY home"><span class="mark">M</span>MAHOGANY</a><button class="workspace-switch" data-action="workspace"><span class="workspace-icon">${icon('building')}</span><span><strong>Northline</strong><small>Sample brokerage</small></span>${icon('down')}</button><div class="nav-label">Workspace</div><nav>${nav('queue','Review queue','tray',need)}${nav('packets','Ready packets','packet',ready)}${nav('activity','Activity','activity')}</nav><div class="sidebar-bottom">${nav('sources','Sources','source')}<button class="nav-item" style="width:100%" data-action="guide">${icon('help')}<span>How it works</span></button><div class="side-note">${icon('shield','small')}<div>Demo mode<br><span style="font-size:12px;color:var(--muted)">Nothing sent. Nothing submitted.</span></div></div></div></aside><div class="main-shell"><header class="topbar"><div class="breadcrumbs"><button class="icon-btn flat mobile-toggle" data-action="menu" aria-label="Open navigation">${icon('menu')}</button><span class="mobile-wordmark">MAHOGANY</span><span class="workspace-crumb">Workspace</span>${icon('chevron','small')}<span class="current">${current}</span>${route==='load'?`${icon('chevron','small')}<span class="current">${e(loadId)}</span>`:''}</div><div class="top-actions"><span class="local-status"><span class="dot"></span>${storageOK?'Saved on this device':'Unsaved · memory only'}</span><button class="btn small secondary" data-action="guide">${icon('eye','small')}Explore the demo</button><button class="avatar" aria-label="About this workspace" data-action="workspace">JD</button></div></header><main class="content" id="main" tabindex="-1">${content}</main></div><nav class="mobile-bottom" aria-label="Mobile navigation">${[['queue','Queue','tray'],['packets','Packets','packet'],['activity','Activity','activity']].map(([name,label,ico])=>`<a href="#/${name}" class="${route===name||(name==='queue'&&route==='load')?'active':''}">${icon(ico)}${label}</a>`).join('')}</nav>`;
}
function footer(){return`<footer class="footer"><span class="safe">${icon('shield')}Sample data only. No live AI, emails, or billing submissions.</span><span>MAHOGANY <span style="margin:0 5px">/</span> Workspace preview 0.2</span></footer>`;}
function heading(eyebrow,title,sub,actions=''){return`<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${actions?`<div class="header-actions">${actions}</div>`:''}</div>`;}
function filteredLoads(){return state.loads.filter(l=>{const a=assess(l),s=(l.id+' '+l.customer+' '+l.carrier+' '+l.origin+' '+l.destination).toLowerCase();return s.includes(query.toLowerCase())&&(route!=='packets'||a.ready)&&(tab!=='attention'||!a.ready)&&(tab!=='ready'||a.ready)&&(filter==='all'||a.state===filter);}).sort((a,b)=>sort==='id'?a.id.localeCompare(b.id,undefined,{numeric:true}):sort==='newest'?Date.parse(b.deliveredAt)-Date.parse(a.deliveredAt):Date.parse(a.deliveredAt)-Date.parse(b.deliveredAt));}
function rowsHTML(){const loads=filteredLoads();if(!loads.length)return`<tr><td colspan="5"><div class="empty"><div class="empty-art">${icon('search','large')}</div><h3>Nothing in this view.</h3><p>Try another search or clear the filters. We’ll keep the queue quiet when there’s nothing to do.</p>${button('Clear filters','clear','secondary small')}</div></td></tr>`;
 return loads.map(l=>{const a=assess(l),first=a.blockers[0];return`<tr class="load-row" data-action="open" data-id="${e(l.id)}" tabindex="0" aria-label="Open load ${e(l.id)}, ${e(l.customer)}, ${STATUS[a.state].label}"><td><div class="load-cell"><span class="load-glyph">${icon('file')}</span><div style="min-width:0"><div class="load-id">${e(l.id)}</div><div class="cell-secondary">${e(l.customer)}</div></div></div></td><td><div class="route-line">${e(l.origin)} ${icon('arrow')}</div><div class="route-second">${e(l.destination)}</div></td><td><div class="doc-count">${icon('packet','small')}<span>${a.done} of ${a.total} checked</span></div><div class="mini-progress" aria-hidden="true">${l.required.map((_,i)=>`<i class="${i<a.done?'filled':''}"></i>`).join('')}</div></td><td>${badge(a)}<div class="status-note">${a.ready?'Packet prepared for human review':a.state==='waiting'?'Request approved in demo · evidence pending':e(first.title)}${a.blockers.length>1?` · +${a.blockers.length-1}`:''}</div></td><td><div class="age-cell"><span>${dateOnly(l.deliveredAt)}</span>${icon('chevron')}</div></td></tr>`;}).join('');}
function updateRows(){const tbody=$('#load-rows');if(tbody)tbody.innerHTML=rowsHTML();const count=$('#queue-result-count');if(count)count.textContent=`${filteredLoads().length} of ${state.loads.length} delivered loads`;}
function queueTable(){const ready=state.loads.filter(l=>assess(l).ready).length;return`<section class="queue-card" aria-label="Delivered load work queue"><div class="queue-toolbar"><div class="tabs" role="tablist" aria-label="Load views">${(route==='packets'?[['all','Ready for review',ready]]:[['all','All loads',state.loads.length],['attention','Needs attention',state.loads.length-ready],['ready','Ready for review',ready]]).map(([id,label,count])=>`<button class="tab ${tab===id?'active':''}" role="tab" aria-selected="${tab===id}" data-action="tab" data-tab="${id}">${label}<span class="counter">${count}</span></button>`).join('')}</div><div class="search-controls"><label class="search">${icon('search','small')}<span class="sr-only">Search loads</span><input id="load-search" type="search" value="${e(query)}" placeholder="Search loads, customers…" autocomplete="off"><kbd>/</kbd></label><button class="icon-btn" data-action="filters" aria-label="Filter and sort loads" aria-expanded="${filtersOpen}">${icon('filter','small')}</button></div></div>${filtersOpen?`<div class="filter-bar"><label>Issue<select id="status-filter"><option value="all">All issues</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${filter===k?'selected':''}>${v.label}</option>`).join('')}</select></label><label>Order<select id="sort-order"><option value="oldest" ${sort==='oldest'?'selected':''}>Oldest delivery first</option><option value="newest" ${sort==='newest'?'selected':''}>Newest delivery first</option><option value="id" ${sort==='id'?'selected':''}>Load number</option></select></label>${button('Clear','clear','ghost small')}</div>`:''}<table class="load-table"><thead><tr><th scope="col">LOAD / CUSTOMER</th><th scope="col">ROUTE</th><th scope="col">DOCUMENTS</th><th scope="col">STATUS / BLOCKER</th><th scope="col">DELIVERED</th></tr></thead><tbody id="load-rows">${rowsHTML()}</tbody></table><div class="queue-bottom"><span id="queue-result-count">${filteredLoads().length} of ${state.loads.length} delivered loads</span><span class="keyboard-tip">Select a load to see the evidence ${icon('arrow','small')}</span></div></section>`;}
function queuePage(){const ready=state.loads.filter(l=>assess(l).ready).length,wait=state.loads.filter(l=>assess(l).state==='waiting').length;return heading('Post-delivery workspace','A clear path to billing.','Know what’s missing. See the evidence. Move the right loads forward.',button('Import sample loads','import','secondary','plus'))+`<section class="overview" aria-label="Current sample workload"><div class="stat"><div class="stat-top">Delivered loads ${icon('tray')}</div><div class="stat-number"><strong>${String(state.loads.length).padStart(2,'0')}</strong><span>in this workspace</span></div></div><div class="stat"><div class="stat-top">Need attention ${icon('clock')}</div><div class="stat-number"><strong>${String(state.loads.length-ready).padStart(2,'0')}</strong><span>${wait} awaiting evidence</span></div></div><div class="stat"><div class="stat-top">Ready for review ${icon('check')}</div><div class="stat-number"><strong>${String(ready).padStart(2,'0')}</strong><span>not yet billing-approved</span></div></div></section>`+queueTable()+`<section class="suggestion"><div class="suggestion-art" aria-hidden="true">${icon('check')}</div><div><h3>One clearer copy. One less blocker.</h3><p>Follow load 1042 from a cropped delivery document to a review-ready packet.</p></div>${button('Review load 1042','open','secondary small','arrow','data-id="1042"')}</section>`+footer();}
function packetsPage(){return heading('Ready packets','The paperwork is in order.','Inspect the complete evidence packet. Final billing decisions stay with your team.')+queueTable()+`<div class="info-strip">${icon('shield')}<p><strong>Ready for review is not approval for billing.</strong><br>Open a load to inspect its documents and export a ZIP with sample PDFs, the checklist, source records, and activity history.</p></div>`+footer();}
function timelineHTML(events,withLoad=false){return`<div class="timeline">${[...events].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).map(ev=>`<div class="timeline-row"><div class="tl-meta"><span>${e(ev.actor)}${withLoad?` · <a href="#/load/${e(ev.loadId)}">Load ${e(ev.loadId)}</a>`:''}</span><time>${formatTime(ev.at)}</time></div><p class="tl-text">${e(ev.text)}</p></div>`).join('')}</div>`;}
function activityPage(){const events=state.loads.flatMap(l=>l.events.map(ev=>({...ev,loadId:l.id})));return heading('Workspace history','Every step, accounted for.','A local record of sample evidence, approvals, and reassessments.')+`<section class="panel activity-page"><div class="panel-title"><h2>Activity trail</h2><span>${events.length} events · stored on this device</span></div>${timelineHTML(events,true)}</section>`+footer();}
function sourcesPage(){return heading('Evidence sources','Check before you chase.','The first version uses a controlled, fictional snapshot. No business accounts are connected.')+`<div class="grid-three"><section class="panel source-card"><div class="source-icon">${icon('file')}</div><h3>Shipment snapshot</h3><span class="tag green">Sample CSV</span><p>Delivered-load records with source and timestamp. These are fictional records, not independently verified delivery events.</p>${button('Import sample CSV','import','secondary small','upload')}</section><section class="panel source-card"><div class="source-icon">${icon('mail')}</div><h3>Document mailbox</h3><span class="tag neutral">Simulated source</span><p>Seeded documents demonstrate missing files, cropped pages, uncertain matches, and a deliberately unavailable source on load 1048.</p>${button('Inspect source gap','open','secondary small','arrow','data-id="1048"')}</section><section class="panel source-card"><div class="source-icon">${icon('source')}</div><h3>Live integrations</h3><span class="tag neutral">Not connected</span><p>TMS access, carrier messaging, OCR, and AI document checks are not active in this prototype. Files are not sent to a remote server.</p>${button('Read prototype limits','workspace','secondary small','help')}</section></div><div class="info-strip">${icon('shield')}<p><strong>An unavailable source is not a missing document.</strong><br>MAHOGANY keeps the assessment incomplete until the required source has been checked. Rechecking a simulated failed source does not silently turn it into a working integration.</p></div>`+footer();}
function docViewer(l){const docs=l.docs.filter(d=>!d.superseded);let doc=docs.find(d=>d.id===selectedDoc)||docs[0];if(doc)selectedDoc=doc.id;
 const img=doc&&(ASSETS[doc.asset]?.image||(doc.data?.startsWith('data:image/')?doc.data:null));
 return`<section class="panel evidence-panel"><div class="panel-title"><h2>Original evidence</h2><span>${docs.length} document${docs.length===1?'':'s'}</span></div><div class="document-tabs" role="tablist" aria-label="Sample documents">${docs.map(d=>`<button role="tab" aria-selected="${doc?.id===d.id}" class="doc-tab ${doc?.id===d.id?'active':''}" data-action="document" data-id="${e(d.id)}">${icon('file')}${d.type==='pod'?'Proof of delivery':d.type==='rate'?'Rate confirmation':d.type==='invoice'?'Invoice':'Added file'}</button>`).join('')||'<span class="fine">No files in the checked sample source.</span>'}</div>${doc?`<div class="viewer-tools"><span class="filename" title="${e(doc.name)}">${e(doc.name)}</span><div class="zoom-tools"><button class="icon-btn" data-action="zoom-out" aria-label="Zoom out">${icon('minus','small')}</button><span id="zoom-label">${zoom}%</span><button class="icon-btn" data-action="zoom-in" aria-label="Zoom in">${icon('plus','small')}</button><button class="icon-btn" data-action="download-doc" aria-label="Download original document">${icon('download','small')}</button></div></div>${img?`<div class="paper-stage"><img id="paper-image" src="${e(img)}" style="width:${zoom}%" alt="${e(TYPE_NAMES[doc.type]||doc.name)} for sample load ${e(l.id)}. ${!doc.complete?'The image ends before the receiving-signature area.':doc.notation?'A damage notation is present.':'Inspect the full document before making a decision.'}"></div>`:`<div class="file-preview-empty"><div>${icon('file')}<p>${doc.data?'This added PDF is available to download for manual inspection. No automated reading has been performed.':'No preview is available.'}</p>${button('Download document','download-doc','secondary small','download')}</div></div>`}<div class="evidence-caption">${icon(doc.match?'check':'alert')}<span class="${doc.match?'':'unmatched'}">${doc.match?'Load reference matches sample record':'Load match is unconfirmed'}</span><span>·</span><span>Page 1 of 1${doc.reviewed?' · seeded metadata':' · unassessed file'}</span></div>`:`<div class="file-preview-empty"><div>${icon('file')}<p>No document has been found in this sample source.<br>Check the assessment before requesting a new copy.</p></div></div>`}<details class="source-details"><summary>${icon('source')}Source and matching evidence</summary><dl><dt>Delivery source</dt><dd>${e(l.deliverySource)}</dd><dt>Recorded delivery</dt><dd>${formatTime(l.deliveredAt)}</dd>${doc?`<dt>Document source</dt><dd>${e(doc.source)}</dd><dt>File reference</dt><dd>${e(doc.reference||'Not extracted')}</dd><dt>Expected reference</dt><dd>${e(l.id)}</dd><dt>Assessment</dt><dd>${doc.reviewed?'Seeded demo metadata. Not live AI analysis.':'Unassessed. A person must inspect the file.'}</dd>`:''}</dl></details></section>`;
}
function assessmentPanel(l){const a=assess(l);return`<section class="panel assessment-panel"><div class="assessment-head"><div class="eyebrow">Paperwork assessment</div><h2>${a.ready?'Ready for a second set of eyes.':'What’s holding this up?'}</h2><p>${a.ready?'All configured sample requirements appear satisfied.':`${a.blockers.length} unresolved item${a.blockers.length===1?'':'s'} · Northline demo checklist`}</p></div>${a.ready?`<div class="ready-callout">${icon('check')}<div><h3>Ready for billing review</h3><p>Evidence is assembled. No invoice has been submitted, and billing has not been approved.</p></div></div>`:`<div class="blockers">${a.blockers.map(b=>`<div class="blocker ${['match','exception','manual'].includes(b.kind)?'review':b.kind==='source'?'source':''}"><div class="blocker-head">${icon(b.kind==='source'?'source':'alert')}<span>${e(b.title)}</span></div><p>${e(b.detail)}</p></div>`).join('')}</div>`}<div class="checklist"><div class="section-label">Required for this packet</div>${a.checks.map(c=>`<div class="check-row" title="${e(c.detail)}"><span class="check-circle ${c.state}">${icon(c.state==='pass'?'check':c.state==='unknown'?'minus':'dot')}</span><span>${e(c.label)}</span><span class="check-right">${{pass:'Checked',fail:'Unresolved',review:'Review',unknown:'Unknown'}[c.state]}</span></div>`).join('')}</div><div class="action-area">${l.pendingRequest&&!a.ready?`<div class="pending-note">${icon('clock','small')}Demo follow-up approved. Evidence still pending.</div>`:''}<p class="fine">${a.ready?'Export the evidence, checklist, and audit trail for a person to review.':a.state==='review'?'Matching and commercial exceptions stay on hold for a qualified reviewer.':!a.sourcesOK?'Recheck the approved source before making a paperwork request.':l.pendingRequest?'A reply without an attachment does not finish the task. No duplicate request is needed.':'A specific request is prepared from the unresolved items. You control the wording and approval.'}</p>${a.ready?button('Export review packet','export-packet','primary full','download'):a.state==='review'?button('Record a review note','note','primary full','note'):!a.sourcesOK?button('Recheck sample sources','recheck','primary full','refresh'):l.pendingRequest?button('View approved draft','view-draft','secondary full','mail'):button('Review follow-up','draft','primary full','mail')}${!a.ready&&a.state!=='review'?button('Record a note','note','ghost small full','note'):''}</div></section>`;}
function detailPage(){const l=currentLoad(),a=assess(l),i=state.loads.indexOf(l);return`<div class="detail-top"><a class="btn ghost" href="#/queue">${icon('back','small')}Back to queue</a><div class="detail-nav"><button class="icon-btn" data-action="previous" aria-label="Previous load" ${i===0?'disabled':''}>${icon('back','small')}</button><button class="icon-btn" data-action="next" aria-label="Next load" ${i===state.loads.length-1?'disabled':''}>${icon('arrow','small')}</button></div></div><div class="detail-heading"><div><div class="detail-title"><h1>Load ${e(l.id)}</h1>${badge(a)}</div><div class="detail-meta"><strong>${e(l.customer)}</strong><span>·</span>${e(l.origin)}${icon('arrow')}${e(l.destination)}<span>·</span>${e(l.carrier)}</div><div class="delivered-note">Recorded delivered ${formatTime(l.deliveredAt)} · imported sample status, not independently verified</div></div></div><div class="detail-layout"><div>${docViewer(l)}<section class="panel timeline-panel"><div class="panel-title"><h2>Evidence & activity</h2><span>${l.events.length} events</span></div>${timelineHTML(l.events)}</section></div><aside class="detail-aside">${assessmentPanel(l)}<section class="demo-tools"><div class="eyebrow">Try the workflow</div><p>Simulate a reply or add a sample file. Nothing leaves this browser.</p>${button('Add sample response','response','secondary small','plus',REPLACEMENTS[l.id]?'':'disabled')}${!a.sourcesOK?button('Restore sample source','restore-source','secondary small','refresh'):''}${button('Add sample file','upload','ghost small','upload')}<p style="font-size:12px;margin-top:7px">Readiness uses sample metadata, not live document analysis.</p></section></aside></div>`+footer();}
function render(){const content=route==='queue'?queuePage():route==='packets'?packetsPage():route==='activity'?activityPage():route==='sources'?sourcesPage():detailPage();$('#app').innerHTML=shell(content);document.title=`${route==='load'?'Load '+loadId+' · ':''}MAHOGANY — Paperwork, ready for review`;}
function openModal(brow,title,body,foot,context={}){
 previousFocus=document.activeElement;modalContext=context;
 $('#modals').innerHTML=`<div class="shade" data-action="shade"><section class="modal ${context.wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><header class="modal-head"><div><div class="eyebrow">${brow}</div><h2 id="dialog-title">${title}</h2></div><button class="icon-btn flat" aria-label="Close dialog" data-action="close">${icon('close')}</button></header><div class="modal-body">${body}<div class="form-error" id="modal-error" role="alert"></div></div>${foot?`<footer class="modal-foot">${foot}</footer>`:''}</section></div>`;
 document.body.style.overflow='hidden';requestAnimationFrame(()=>$('#modals .modal')?.focus());
}
function closeModal(){if(!$('#modals').innerHTML)return;$('#modals').innerHTML='';modalContext=null;document.body.style.overflow='';if(previousFocus?.isConnected)previousFocus.focus();}
function modalError(message){const target=$('#modal-error');if(target){target.textContent=message;target.classList.add('visible');target.scrollIntoView({block:'nearest'});}else toast(message,true);}
function guide(){openModal('A two-minute walkthrough','From held up to handed over.',`<p>Explore one complete paperwork loop using load 1042. All records and responses are fictional.</p><div class="steps"><div class="guide-step"><span class="step-num">1</span><div><h3>See the blocker.</h3><p>Open the proof of delivery. The page ends before the receiving-signature area.</p></div></div><div class="guide-step"><span class="step-num">2</span><div><h3>Review the next action.</h3><p>Edit the follow-up and approve it in demo mode. No carrier is contacted.</p></div></div><div class="guide-step"><span class="step-num">3</span><div><h3>Try a reply without evidence.</h3><p>Choose “A promise, no attachment.” The load correctly stays unresolved.</p></div></div><div class="guide-step"><span class="step-num">4</span><div><h3>Bring in a clearer copy.</h3><p>Add the clean sample POD. Inspect the updated checklist and export the review packet.</p></div></div></div><div class="demo-disclaimer" style="margin-top:17px">${icon('shield')}<span>This is a local workflow prototype. Document findings are seeded, not generated by live AI. Reset the sample workspace from the workspace menu to repeat the original walkthrough.</span></div>`,button('Keep exploring','close','secondary')+button('Open load 1042','start-guide','primary','arrow'));}
function workspace(){openModal('MAHOGANY / version 0.2','A sample workspace. A real workflow.',`<p>This prototype is separate from DESK. It demonstrates post-delivery document review for the fictional Northline Brokerage.</p><div class="demo-disclaimer">${icon('shield')}<span><strong>Local only.</strong> Sample records, notes, approvals, and added files stay in this browser’s storage. No telemetry, remote uploads, live inbox access, TMS writes, or message sending is enabled.</span></div><div class="rule"></div><p><strong>What works:</strong> search, filtering, evidence previews, editable drafts, approval history, sample replies, checklist reassessment, local file attachment, CSV import, and ZIP packet export.</p><p><strong>What is simulated:</strong> shipment records, source checks, document extraction and assessment, carrier responses, and delivery status. This is not production software or a security boundary for business data.</p><p class="fine">Use fictional or redacted sample data only. Storage is device-specific and can be cleared by your browser. No authentication or shared backend is present.</p>`,button('Reset sample workspace','reset','secondary','refresh')+button('Back to workspace','close','primary'));}
function openDraft(view=false){const l=currentLoad();const draft=view?l.pendingRequest:l.draft||followupDraft(l);if(!draft)return;openModal(view?'Recorded approval / demo only':'Outreach / human approval',view?'The approved follow-up.':'Ask for exactly what’s missing.',`<p>${view?'This message was approved in the simulation. It was not sent.':'A draft based on the unresolved sample requirements. Review the recipient and wording before approving.'}</p><label class="field"><span>To · fictional recipient</span><input value="${e(l.email)}" readonly aria-label="Fictional recipient"></label><label class="field"><span>Subject</span><input id="draft-subject" value="${e(draft.subject)}" maxlength="200" ${view?'readonly':''}></label><label class="field"><span>Message</span><textarea id="draft-body" maxlength="5000" ${view?'readonly':''}>${e(draft.body)}</textarea></label><div class="demo-disclaimer">${icon('shield')}<span>Approval records an action in this demo only. No email is sent, and no customer or carrier is contacted.</span></div>`,view?button('Copy message','copy-draft','secondary','copy')+button('Done','close','primary'):button('Save draft','save-draft','secondary')+button('Approve in demo','approve-draft','primary','check'),{type:'draft',id:l.id});}
function responseModal(){const l=currentLoad();openModal('Simulate incoming evidence','What comes back?',`<p>Choose a fictional response for load ${e(l.id)}. Findings come from known sample metadata, not live document analysis.</p><button class="choice" data-action="receive" data-kind="promise">${icon('mail')}<div><strong>A promise, no attachment</strong><span>“I’ll send it shortly.” The task stays open.</span></div>${icon('arrow','arrow')}</button><button class="choice" data-action="receive" data-kind="pod">${icon('file')}<div><strong>A clear, signed POD</strong><span>Add a complete sample delivery document. Other blockers stay unresolved.</span></div>${icon('arrow','arrow')}</button><button class="choice" data-action="receive" data-kind="packet">${icon('packet')}<div><strong>POD and carrier invoice</strong><span>Add both sample documents. Any commercial exception or source gap still stays on hold.</span></div>${icon('arrow','arrow')}</button><div class="demo-disclaimer">${icon('eye')}<span>Earlier attachments remain in the evidence history. A clean replacement never silently clears an earlier damage notation.</span></div>`,button('Cancel','close','secondary'),{id:l.id});}
function noteModal(){const l=currentLoad();openModal('Human review','Leave a clear handoff.',`<p>Record your observation or the next person who should review this load. A note does not approve billing or clear an unresolved exception.</p><label class="field note-form"><span>Review note</span><textarea id="review-note" maxlength="2000" placeholder="For example: damaged-carton notation needs review by the billing lead before this packet moves forward."></textarea></label>`,button('Cancel','close','secondary')+button('Save review note','save-note','primary','note'),{id:l.id});}
function importModal(){pendingImport=[];openModal('Local import / sample data only','Bring in a sample snapshot.',`<p>Import delivered loads from a CSV. New loads stay <strong>Assessment incomplete</strong> until a document source can be checked. No live system is contacted.</p><div class="sample-import-info">Use up to 200 fictional records. Each row must include a delivered timestamp with a timezone.<code>load_id,customer,carrier,origin,destination,delivered_at</code></div><p style="margin-top:14px">${button('Get sample CSV','sample-csv','ghost small','download')}</p><label class="field"><span>Choose a CSV · maximum 1 MB</span><input id="csv-input" type="file" accept=".csv,text/csv"></label><div id="import-preview" class="import-preview"></div><div class="demo-disclaimer">${icon('shield')}<span>Use sample data only. This prototype stores records on this device and has no production privacy or access controls.</span></div>`,button('Cancel','close','secondary')+button('Import loads','confirm-import','primary','upload','disabled id="confirm-import"'),{type:'import'});}
function uploadModal(){const l=currentLoad();openModal('Manual evidence / local only','Add a sample document.',`<p>Attach a fictional PDF, PNG, or JPEG to load ${e(l.id)}. The file will remain <strong>unassessed</strong>: its name does not prove it matches the load.</p><div class="uploader">${icon('upload','large')}<p>A local file attachment, not an OCR test.<br>Maximum 2 MB. No remote upload.</p><label><span class="sr-only">Select a sample document</span><input type="file" id="evidence-input" accept="application/pdf,image/png,image/jpeg"></label></div><div class="demo-disclaimer" style="margin-top:18px">${icon('alert')}<span>An unassessed attachment prevents a packet from being labeled ready. No arbitrary file is automatically classified or approved in this prototype.</span></div>`,button('Cancel','close','secondary'),{id:l.id});}
function exportPacket(){const l=currentLoad();const manifest=packetManifest(l);const files=[];for(const d of l.docs){const data=ASSETS[d.asset]?.pdf||d.data;if(!data)continue;const name=d.name.replace(/[^A-Za-z0-9._-]/g,'_');files.push({name:(d.superseded?'prior-evidence/':'documents/')+d.id.replace(/[^A-Za-z0-9_-]/g,'_')+'-'+name,data:dataBytes(data)});}
 files.push({name:'review-manifest.json',data:JSON.stringify(manifest,null,2)});files.push({name:'audit-trail.json',data:JSON.stringify(l.events,null,2)});files.push({name:'README.txt',data:`MAHOGANY — FICTIONAL REVIEW PACKET\nLoad ${l.id}\n\nThis packet is ready for a person's review, not approved for billing.\nAll bundled seed documents are fictional. Readiness is computed from sample metadata, not live AI or OCR.\nDo not use this packet for billing, payment, claims, or operational purposes.\n\nThe documents directory contains current evidence. Prior-evidence retains superseded samples.\nreview-manifest.json contains requirements, source provenance, and file matching metadata.\naudit-trail.json contains the local demo history.\n`});
 files.push({name:'review-summary.html',data:`<!doctype html><html lang="en"><meta charset="UTF-8"><title>Sample review packet ${e(l.id)}</title><style>body{font:15px system-ui;max-width:800px;margin:50px auto;padding:20px;color:#29342b}h1{font:40px Georgia}li{margin:12px 0}.notice{padding:20px;background:#f2f2e9;border:1px solid #ddd}p{line-height:1.7}</style><h1>MAHOGANY</h1><h2>Load ${e(l.id)} · Ready for billing review</h2><p class="notice">FICTIONAL DEMO ONLY. Billing is not approved. No real document analysis or delivery verification was performed.</p><p>${e(l.customer)} · ${e(l.origin)} to ${e(l.destination)}<br>${e(l.carrier)}</p><h3>Configured sample requirements</h3><ul>${manifest.checklist.map(c=>`<li>${e(c.label)}: ${e(c.state)} — ${e(c.detail)}</li>`).join('')}</ul><p>Inspect the original PDFs, source records, and activity history before making any decision. This export is a demo artifact, not a commercial record.</p></html>`});
 downloadBlob(makeZip(files),`MAHOGANY-sample-load-${l.id}-review-packet.zip`);const next=copy(l);event(next,'Sample review packet exported. Billing remains unapproved.','export');updateLoad(next);toast('Review packet exported. No billing was approved.');}
async function copyDraft(){const text=$('#draft-body')?.value||'';try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else{const t=$('#draft-body');t.focus();t.select();if(!document.execCommand('copy'))throw new Error();}toast('Message copied. Nothing was sent.');}catch{const t=$('#draft-body');t?.focus();t?.select();toast('Message selected. Use your browser’s Copy command.');}}
async function handleAction(action,el,ev){
 switch(action){
 case'skip-main':$('#main')?.focus();break;
 case'menu':mobileOpen=!mobileOpen;render();break;
 case'open':closeModal();go('#/load/'+el.dataset.id);break;
 case'previous':case'next':{const index=state.loads.findIndex(l=>l.id===loadId)+(action==='next'?1:-1);if(state.loads[index])go('#/load/'+state.loads[index].id);break;}
 case'tab':tab=el.dataset.tab;render();break;
 case'filters':filtersOpen=!filtersOpen;render();break;
 case'clear':query='';filter='all';tab='all';render();break;
 case'document':selectedDoc=el.dataset.id;zoom=100;render();break;
 case'zoom-in':case'zoom-out':zoom=Math.min(170,Math.max(70,zoom+(action==='zoom-in'?10:-10)));if($('#paper-image'))$('#paper-image').style.width=zoom+'%';if($('#zoom-label'))$('#zoom-label').textContent=zoom+'%';break;
 case'guide':guide();break;
 case'workspace':workspace();break;
 case'start-guide':closeModal();go('#/load/1042');break;
 case'close':closeModal();break;
 case'shade':if(ev.target===el)closeModal();break;
 case'draft':openDraft();break;
 case'view-draft':openDraft(true);break;
 case'copy-draft':await copyDraft();break;
 case'save-draft':{const l=copy(getLoad(modalContext.id));const subject=$('#draft-subject').value.trim(),body=$('#draft-body').value.trim();if(!subject||!body)throw new Error('Add a subject and a message before saving.');l.draft={subject,body};event(l,'Follow-up draft saved locally. No message sent.','draft');updateLoad(l);closeModal();toast('Draft saved on this device.');break;}
 case'approve-draft':{const l=getLoad(modalContext.id),draft={subject:$('#draft-subject').value,body:$('#draft-body').value};const next=approveDraft(l,draft);updateLoad(next);closeModal();toast('Approved in demo. No carrier was contacted.');break;}
 case'response':responseModal();break;
 case'receive':{const l=getLoad(modalContext.id);const next=receiveSample(l,el.dataset.kind,REPLACEMENTS[l.id]);updateLoad(next);closeModal();toast(el.dataset.kind==='promise'?'Promise recorded. Evidence is still required.':assess(next).ready?'Sample packet is ready for human review.':'Evidence added. Other blockers remain open.');break;}
 case'note':noteModal();break;
 case'save-note':{const note=$('#review-note').value.trim();if(!note)throw new Error('Write a review note before saving.');const next=copy(getLoad(modalContext.id));next.notes.push({at:new Date().toISOString(),text:note});event(next,note,'note');updateLoad(next);closeModal();toast('Review note saved. Blockers remain unchanged.');break;}
 case'recheck':{const next=copy(currentLoad());event(next,assess(next).sourcesOK?'Sample source snapshot checked again. No live source was contacted.':'Recheck could not access the simulated document source. Assessment remains incomplete.','source','MAHOGANY demo rules');updateLoad(next);toast(assess(next).sourcesOK?'Sample sources checked. No live systems accessed.':'Source still unavailable. No paperwork request was created.');break;}
 case'restore-source':{const next=restoreSampleSource(currentLoad());updateLoad(next);toast('Source restored in the simulation. Checklist reassessed.');break;}
 case'export-packet':exportPacket();break;
 case'download-doc':{const l=currentLoad(),d=l.docs.find(d=>d.id===selectedDoc);if(!d)throw new Error('Choose a document.');const data=ASSETS[d.asset]?.pdf||d.data;if(!data)throw new Error('Document bytes are not available.');downloadBlob(new Blob([dataBytes(data)],{type:data.slice(5,data.indexOf(';'))}),d.name);toast('Original sample document exported.');break;}
 case'import':importModal();break;
 case'sample-csv':downloadBlob(new Blob(['load_id,customer,carrier,origin,destination,delivered_at\n1050,Mason Sample Goods,Sample Carrier,"Dallas, TX","Austin, TX",2026-10-04T16:00:00Z\n1051,Northstar Sample,Sample Linehaul,"Tulsa, OK","Fort Worth, TX",2026-10-04T18:30:00Z\n'],{type:'text/csv'}),'MAHOGANY-sample-loads.csv');break;
 case'confirm-import':{if(!pendingImport.length)throw new Error('Choose a valid CSV first.');const existing=new Set(state.loads.map(l=>l.id));const dup=pendingImport.find(l=>existing.has(l.id));if(dup)throw new Error(`Load ${dup.id} already exists. Nothing was imported.`);if(state.loads.length+pendingImport.length>208)throw new Error('This demo supports up to 208 total records.');const count=pendingImport.length;state.loads.push(...pendingImport);persist();closeModal();query='';tab='all';filter='all';route='queue';go('#/queue');render();toast(`${count} sample loads imported. Document assessment remains incomplete.`);break;}
 case'upload':uploadModal();break;
 case'reset':openModal('Reset demo','Start with a clean desk?',`<p>This resets only MAHOGANY’s local sample workspace. Added files, imported loads, notes, and draft approvals on this device will be removed. The original eight sample loads will be restored.</p><p>Export any sample packets you need before resetting.</p>`,button('Keep my changes','close','secondary')+button('Reset sample data','confirm-reset','primary','refresh'));break;
 case'confirm-reset':state={version:VERSION,loads:copy(SEED)};persist();closeModal();query='';tab='all';filter='all';sort='oldest';filtersOpen=false;go('#/queue');render();toast('The original eight sample loads are restored.');break;
 }
}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el||el.disabled)return;if(el.dataset.action!=='shade')ev.preventDefault();Promise.resolve(handleAction(el.dataset.action,el,ev)).catch(err=>modalContext?modalError(err.message):toast(err.message,true));});
document.addEventListener('input',ev=>{if(ev.target.id==='load-search'){query=ev.target.value;updateRows();}});
document.addEventListener('change',async ev=>{
 if(ev.target.id==='status-filter'){filter=ev.target.value;updateRows();}
 if(ev.target.id==='sort-order'){sort=ev.target.value;updateRows();}
 if(ev.target.id==='csv-input'){
   pendingImport=[];$('#confirm-import').disabled=true;$('#import-preview').innerHTML='';$('#modal-error').classList.remove('visible');const file=ev.target.files[0];if(!file)return;
   try{if(file.size>1_000_000)throw new Error('Use a CSV smaller than 1 MB.');const parsed=parseCSV(await file.text());const dup=parsed.find(l=>getLoad(l.id));if(dup)throw new Error(`Load ${dup.id} already exists. Use unique sample load IDs.`);pendingImport=parsed;$('#import-preview').innerHTML=`<strong>${parsed.length} valid sample loads</strong><ul>${parsed.slice(0,5).map(l=>`<li>${e(l.id)} · ${e(l.customer)} · ${e(l.origin)} → ${e(l.destination)}</li>`).join('')}</ul>`;$('#confirm-import').disabled=false;}catch(err){modalError(err.message);}
 }
 if(ev.target.id==='evidence-input'){
   const file=ev.target.files[0];if(!file)return;const id=modalContext?.id;
   try{if(file.size>2_000_000)throw new Error('Choose a sample file smaller than 2 MB.');if(!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new Error('Use a PDF, PNG, or JPEG sample.');
    const data=await new Promise((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(reader.result);reader.onerror=()=>rej(new Error('The file could not be read.'));reader.readAsDataURL(file);});
    if(!getLoad(id))throw new Error('The load is no longer available.');const l=copy(getLoad(id));l.docs.push({id:'local-'+Date.now(),name:file.name,type:'unclassified',asset:null,data,reference:null,match:false,readable:false,complete:false,signature:false,notation:false,receivedAt:new Date().toISOString(),source:'Local sample upload',superseded:false,reviewed:false});event(l,'Local sample file added: '+file.name+'. Manual assessment required; no automatic extraction was performed.','document');selectedDoc=l.docs.at(-1).id;updateLoad(l);closeModal();toast('Sample file attached. It remains unassessed.');
   }catch(err){modalError(err.message);}
 }
});
document.addEventListener('keydown',ev=>{
 const editing=['INPUT','TEXTAREA','SELECT'].includes(ev.target.tagName)||ev.target.isContentEditable;
 if(ev.key==='Escape'){if(modalContext)closeModal();else if(mobileOpen){mobileOpen=false;render();}return;}
 if(ev.key==='Tab'&&modalContext){const list=[...$('#modals').querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select,a[href]')].filter(x=>x.offsetParent!==null),first=list[0],last=list.at(-1);if(ev.shiftKey&&(document.activeElement===first||document.activeElement.classList.contains('modal'))){ev.preventDefault();last?.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first?.focus();}return;}
 if(ev.key==='/'&&!editing&&!modalContext){const input=$('#load-search');if(input){ev.preventDefault();input.focus();}return;}
 if((ev.key==='Enter'||ev.key===' ')&&ev.target.matches('.load-row')){ev.preventDefault();go('#/load/'+ev.target.dataset.id);}
});
window.addEventListener('hashchange',()=>{closeModal();tab='all';readRoute();});
readRoute();
if(recovered)toast('A previous workspace could not be read. The original sample data is loaded.',true);
